name: Greet Everyone

on: [push]

jobs: 
  build: 

    name: Greeting 

    runs-on: ubuntu-latest

    steps:

      - name: Hello World
        uses: actions/hello-world-javascript-action@v1.1

        with:
          who-to-greet: 'Mona the Octocat'
        
        id: hellow

      - name: Echo the greeting's time 
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
